# Generated by Django 6.0.2 on 2026-03-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='concept',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
