# Generated by Django 6.0.2 on 2026-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0005_alter_question_type_mcq_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='concept',
        ),
    ]
