# Generated by Django 6.0.2 on 2026-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0006_remove_question_concept'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
