# Generated by Django 6.0.2 on 2026-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0007_question_explanation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
