# Generated by Django 6.0.2 on 2026-04-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0011_result_performance_data_alter_result_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institute',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
