# Generated by Django 6.0.2 on 2026-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0015_studymaterial_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
