# Generated by Django 6.0.2 on 2026-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0016_question_topic_question_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.AddField(
            model_name='question',
            name='alternate_correct_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='alternate_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
