# Generated by Django 6.0.2 on 2026-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prep', '0017_remove_question_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='alternate_explanation_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
